const cards = [
    {
        _id: "eafeswfwr2326346tf3254f",
        title: "Meta",
        subtitle: "Meta Platforms, Inc.",
        description: "Meta is an American multinational technology conglomerate. The company owns and operates Facebook, Instagram, Threads, and WhatsApp, among other products and services",
        phone: "(650) 543-4800",
        email: "support@fb.com",
        web: "https://www.meta.com",
        image: {
            url: "https://i0.wp.com/www.almanacnews.com/wp-content/uploads/2022/11/61744_original-1.jpg",
            alt: "image",
        },
        address: {
            state: "CA",
            country: "USA",
            street: "Hacker Wy",
            houseNumber: 1,
            city: "Menlo Park",
            zip: 94025,
        },
        bizNumber: 1111111,
        likes: [],
        user_id: "jenniferabcdefg123",
    },
    {
        _id: "daslfjhbasfjba123124123",
        title: "Google",
        subtitle: "Google LLC",
        description: "Google LLC is an American multinational technology company focusing on artificial intelligence, online advertising, search engine technology, cloud computing, computer software, quantum computing, e-commerce, and consumer electronics",
        phone: "(650) 253-0000",
        email: "support@google.com",
        web: "https://www.google.com",
        image: {
            url: "https://upload.wikimedia.org/wikipedia/commons/3/32/Googleplex_HQ_%28cropped%29.jpg",
            alt: "image",
        },
        address: {
            state: "CA",
            country: "USA",
            street: "Amphitheatre Parkway",
            houseNumber: 1600,
            city: "Mountain View",
            zip: 94043,
        },
        bizNumber: 222222,
        likes: [],
        user_id: "4235234234mfnjrb2h3vbry23",
    },
    {
        _id: "asdfaa54sdf158as4ass",
        title: "Amazon",
        subtitle: "Amazon.com",
        description: "Amazon, is an American multinational technology company focusing on e-commerce, cloud computing, online advertising, digital streaming, and artificial intelligence",
        phone: "(206) 266-1000",
        email: "primary@amazon.com",
        web: "https://www.amazon.com",
        image: {
            url: "https://amazon-blogs-brightspot.s3.amazonaws.com/1f/9f/75d404c9438999db2e2f8b7c7ea6/amazon-seattle-office-headquarters.jpeg",
            alt: "image",
        },
        address: {
            state: "WA",
            country: "USA",
            street: "Terry Ave N",
            houseNumber: 440,
            city: "Seattle",
            zip: 98109,
        },
        bizNumber: 333333,
        likes: [],
        user_id: "4235234234mfnjasdasdry23",
    },
    {
        _id: "asdfaa54sdf158as4jen",
        title: "Microsoft",
        subtitle: "Microsoft Corporation",
        description: "Microsoft Corporation is an American multinational technology corporation. Microsoft's best-known software products are the Windows line of operating systems, the Microsoft 365 suite of productivity applications, and the Edge web browser.",
        phone: "(425) 882-8080",
        email: "support@microsoft.com",
        web: "https://www.microsoft.com",
        image: {
            url: "https://upload.wikimedia.org/wikipedia/commons/3/30/Building92microsoft.jpg",
            alt: "image",
        },
        address: {
            state: "WA",
            country: "USA",
            street: "Microsoft Way",
            houseNumber: 1,
            city: "Redmond",
            zip: 98052,
        },
        bizNumber: 444444,
        likes: [],
        user_id: "jenniferabcdefg123",
    },
];

exports.cards = cards;